#!/usr/bin/python3
def prime_generator(num = 0):
    full_list = [i for i in range(2, int(num ** 0.5))]
    for i in full_list:
        for j in full_list:
            if i % j == 0 and i != j:
                full_list.remove(j)
    return full_list

prime_generator(20)
