#!/usr/bin/python3
from sys import argv
import math
# open the file
with open(argv[1], "r", encoding="utf-8") as f:
    # read the number 
    num = f.read()
    num = int(num)
    # generate a range of numbers
    sq = num // 2
    prime_list = [i for i in range(2, sq+1)]
    # generate prime numbers
    for x in range(int(math.sqrt(sq))):
        prime = prime_list[x]
        for j in prime_list:
            if prime != j and j % prime == 0:
                prime_list.remove(j)
    # generate a prime product
    div = 0
    for x in prime_list:
        if num % x == 0:
            div = num // x
            break
    print(f"{num}={div}*{x}")
